version: '3.7'

services:
    php:
        build: docker/php
        volumes:
            - ./www/1944:/var/www/html
        links:
            - mysql
        networks:
            app_net:
                ipv4_address: 172.158.11.2


    mysql:
        image: mysql:5.6.47
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            app_net:
                ipv4_address: 172.158.11.3

volumes:
    mysql:

networks:
    app_net:
        ipam:
            driver: default
            config:
                - subnet: "172.158.11.0/24"
